/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.MainDAO;
import Model.ChuyenBay;
import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class frmMain extends javax.swing.JFrame {

    int showHideMenu = 1;
    int showHideSubMenu_ThanhToan = 1;
    int showHideSubMenu_Ve = 1;
    int showHideSubMenu_ChuyenBay = 1;
    String chucVu = "";
    private JPanel pnlSubQuanLyNhapHang;

    void checkUser() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        chucVu = frmLogin.vt;
                        String ten = new MainDAO().getHoTen(frmLogin.tenDN);
                        if (ten.isEmpty()) {
                            lblUser.setText("NULL");
                        } else {
                            lblUser.setText(ten);
                            lblChucVu.setText(frmLogin.vt);
                        }
                        Thread.sleep(100);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }.start();
    }

    void close() {
        this.dispose();
    }

    void minus() {
        this.setState(1);
    }

    void loadOpenForm() {
        for (double i = 0.0; i < 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.parseFloat(val);
            this.setOpacity(f);
            try {
                Thread.sleep(70);
            } catch (Exception e) {
            }
        }
    }

    void hover(int so, JPanel pnl) {
        if (so == 1) {
            pnl.setBackground(new Color(122, 89, 186));
            pnl.setCursor(new Cursor(HAND_CURSOR));
        } else {
            pnl.setBackground(new Color(55, 38, 91));
        }
    }

    void changeIcon(int so, JButton btn, String url) {
        if (so == 1) {
            Image img = getToolkit().createImage(url);
            btn.setIcon(new ImageIcon(img));
            btn.setCursor(new Cursor(HAND_CURSOR));
        } else {
            Image img = getToolkit().createImage(url);
            btn.setIcon(new ImageIcon(img));
        }
    }

    void menu() {
        showHideMenu++;
        if (showHideMenu % 2 == 0) {
            pnlNavigation.setBackground(new Color(55, 38, 91));
            pnlMenu.setSize(60, 800);
            btnMenu.setLocation(80, 20);
            lblSlogan.setLocation(130, 23);
        } else {
            pnlNavigation.setBackground(new Color(83, 62, 128));
            pnlMenu.setSize(230, 800);
            btnMenu.setLocation(250, 20);
            lblSlogan.setLocation(300, 23);
        }
    }

    void showHideSubMenu(int so, JPanel panel) {
        so++;
        if (so % 2 == 0) {
            pnlSubMenu.setVisible(true);
        } else {
            pnlSubMenu.setVisible(false);
        }
        JPanel[] pnl = new JPanel[]{pnlSubThanhToan, pnlSubQuanLyGiay, pnlSubQuanLyNhapHang};
        for (int i = 0; i < pnl.length; i++) {
            pnl[i].setVisible(false);
        }
        panel.setVisible(true);
    }

    void login() {
        new frmLogin().setVisible(true);
    }

    public frmMain() {
        initComponents();
        setLocationRelativeTo(this);
        checkUser();
        pnlSubMenu.setVisible(false);
        tbpForm.setBackground(new Color(0, 0, 0, 0));
        tbpForm.removeAll();
        frmTrangChu tc = new frmTrangChu();
        tbpForm.addTab("", null, tc.getContentPane().getComponentAt(0, 0), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblChucVu = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlTrangChu = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JButton();
        pnlKhachHang = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JButton();
        pnlNhanVien = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        pnlThanhToan = new javax.swing.JPanel();
        btnThanhtoan = new javax.swing.JButton();
        pnlQuanLyGiay = new javax.swing.JPanel();
        btnQuanLyGiay = new javax.swing.JButton();
        pnlQuanLyNhapHang = new javax.swing.JPanel();
        btnQuanLyNhapHang = new javax.swing.JButton();
        pnlNavigation = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        pnlQuanLyDoanhThu = new javax.swing.JPanel();
        btnDoanhThuTheoQuy = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblSlogan = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        pnlSubMenu = new javax.swing.JPanel();
        pnlSubQuanLyGiay = new javax.swing.JPanel();
        pnlSubQuanLyGiay_Giay = new javax.swing.JPanel();
        btnGiay = new javax.swing.JButton();
        pnlSubQuanLyGiay_DichVu = new javax.swing.JPanel();
        btnDichVu = new javax.swing.JButton();
        javax.swing.JPanel pnlSubQuanLyNhapHang = new javax.swing.JPanel();
        pnlSubQuanLyNhapHang_ChuyenBayNhapHang = new javax.swing.JPanel();
        btnChuyenBayNhap = new javax.swing.JButton();
        pnlSubQuanLyNhapHang_HangGiay = new javax.swing.JPanel();
        btnHangGiay = new javax.swing.JButton();
        pnlSubQuanLyNhapHang_NhapHang = new javax.swing.JPanel();
        btnNhapHang = new javax.swing.JButton();
        pnlSubThanhToan = new javax.swing.JPanel();
        pnlSubThanhToan_HD = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        pnlSubThanhToan_HDCT = new javax.swing.JPanel();
        btnHDCT = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        tbpForm = new javax.swing.JTabbedPane();
        pnlFooter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChucVu.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlMenu.add(lblChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, 20));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        lblUser.setText("SNKA SHOES");
        pnlMenu.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        pnlTrangChu.setBackground(new java.awt.Color(51, 51, 51));

        btnTrangChu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        btnTrangChu.setBorder(null);
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setContentAreaFilled(false);
        btnTrangChu.setDefaultCapable(false);
        btnTrangChu.setFocusPainted(false);
        btnTrangChu.setFocusable(false);
        btnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrangChu.setIconTextGap(25);
        btnTrangChu.setLabel("Trang chủ");
        btnTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangChuMouseExited(evt);
            }
        });
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTrangChuLayout = new javax.swing.GroupLayout(pnlTrangChu);
        pnlTrangChu.setLayout(pnlTrangChuLayout);
        pnlTrangChuLayout.setHorizontalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangChuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTrangChuLayout.setVerticalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 230, -1));

        pnlKhachHang.setBackground(new java.awt.Color(51, 51, 51));

        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khachHang.png"))); // NOI18N
        btnKhachHang.setText("Quản lý khách hàng");
        btnKhachHang.setBorder(null);
        btnKhachHang.setBorderPainted(false);
        btnKhachHang.setContentAreaFilled(false);
        btnKhachHang.setDefaultCapable(false);
        btnKhachHang.setFocusPainted(false);
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachHang.setIconTextGap(25);
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseExited(evt);
            }
        });
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 230, -1));

        pnlNhanVien.setBackground(new java.awt.Color(51, 51, 51));

        btnNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/officer.png"))); // NOI18N
        btnNhanVien.setText("Quản lý nhân sự");
        btnNhanVien.setBorder(null);
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setContentAreaFilled(false);
        btnNhanVien.setDefaultCapable(false);
        btnNhanVien.setFocusPainted(false);
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.setIconTextGap(25);
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseExited(evt);
            }
        });
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 302, -1, -1));

        pnlThanhToan.setBackground(new java.awt.Color(51, 51, 51));

        btnThanhtoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/money.png"))); // NOI18N
        btnThanhtoan.setText("Thanh toán");
        btnThanhtoan.setBorder(null);
        btnThanhtoan.setBorderPainted(false);
        btnThanhtoan.setContentAreaFilled(false);
        btnThanhtoan.setDefaultCapable(false);
        btnThanhtoan.setFocusPainted(false);
        btnThanhtoan.setFocusable(false);
        btnThanhtoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThanhtoan.setIconTextGap(25);
        btnThanhtoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThanhtoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThanhtoanMouseExited(evt);
            }
        });
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThanhToanLayout = new javax.swing.GroupLayout(pnlThanhToan);
        pnlThanhToan.setLayout(pnlThanhToanLayout);
        pnlThanhToanLayout.setHorizontalGroup(
            pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThanhToanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlThanhToanLayout.setVerticalGroup(
            pnlThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, -1));

        pnlQuanLyGiay.setBackground(new java.awt.Color(51, 51, 51));

        btnQuanLyGiay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuanLyGiay.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyGiay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ticket.png"))); // NOI18N
        btnQuanLyGiay.setText("Quản lý giày");
        btnQuanLyGiay.setBorder(null);
        btnQuanLyGiay.setBorderPainted(false);
        btnQuanLyGiay.setContentAreaFilled(false);
        btnQuanLyGiay.setDefaultCapable(false);
        btnQuanLyGiay.setFocusPainted(false);
        btnQuanLyGiay.setFocusable(false);
        btnQuanLyGiay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyGiay.setIconTextGap(25);
        btnQuanLyGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyGiayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyGiayMouseExited(evt);
            }
        });
        btnQuanLyGiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyGiayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyGiayLayout = new javax.swing.GroupLayout(pnlQuanLyGiay);
        pnlQuanLyGiay.setLayout(pnlQuanLyGiayLayout);
        pnlQuanLyGiayLayout.setHorizontalGroup(
            pnlQuanLyGiayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuanLyGiayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuanLyGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuanLyGiayLayout.setVerticalGroup(
            pnlQuanLyGiayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuanLyGiay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlQuanLyGiay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 230, -1));

        pnlQuanLyNhapHang.setBackground(new java.awt.Color(51, 51, 51));

        btnQuanLyNhapHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuanLyNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/clock.png"))); // NOI18N
        btnQuanLyNhapHang.setText("Quản lý nhập giày");
        btnQuanLyNhapHang.setBorder(null);
        btnQuanLyNhapHang.setBorderPainted(false);
        btnQuanLyNhapHang.setContentAreaFilled(false);
        btnQuanLyNhapHang.setDefaultCapable(false);
        btnQuanLyNhapHang.setFocusPainted(false);
        btnQuanLyNhapHang.setFocusable(false);
        btnQuanLyNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyNhapHang.setIconTextGap(25);
        btnQuanLyNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyNhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyNhapHangMouseExited(evt);
            }
        });
        btnQuanLyNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhapHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyNhapHangLayout = new javax.swing.GroupLayout(pnlQuanLyNhapHang);
        pnlQuanLyNhapHang.setLayout(pnlQuanLyNhapHangLayout);
        pnlQuanLyNhapHangLayout.setHorizontalGroup(
            pnlQuanLyNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuanLyNhapHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuanLyNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuanLyNhapHangLayout.setVerticalGroup(
            pnlQuanLyNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuanLyNhapHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlQuanLyNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 478, 230, -1));

        pnlNavigation.setBackground(new java.awt.Color(0, 0, 0));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setDefaultCapable(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/setting.png"))); // NOI18N
        btnSetting.setBorder(null);
        btnSetting.setBorderPainted(false);
        btnSetting.setContentAreaFilled(false);
        btnSetting.setDefaultCapable(false);
        btnSetting.setFocusPainted(false);
        btnSetting.setFocusable(false);
        btnSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingMouseExited(evt);
            }
        });
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });

        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/group.png"))); // NOI18N
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.setContentAreaFilled(false);
        btnAccount.setDefaultCapable(false);
        btnAccount.setFocusPainted(false);
        btnAccount.setFocusable(false);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccountMouseExited(evt);
            }
        });
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSetting)
                .addGap(18, 18, 18)
                .addComponent(btnAccount)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAccount)
                    .addComponent(btnSetting)
                    .addComponent(btnLogout))
                .addContainerGap())
        );

        pnlMenu.add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 758, 230, -1));

        pnlQuanLyDoanhThu.setBackground(new java.awt.Color(51, 51, 51));

        btnDoanhThuTheoQuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoanhThuTheoQuy.setForeground(new java.awt.Color(255, 255, 255));
        btnDoanhThuTheoQuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plan.png"))); // NOI18N
        btnDoanhThuTheoQuy.setText("Doanh thu quý ");
        btnDoanhThuTheoQuy.setBorder(null);
        btnDoanhThuTheoQuy.setBorderPainted(false);
        btnDoanhThuTheoQuy.setContentAreaFilled(false);
        btnDoanhThuTheoQuy.setFocusPainted(false);
        btnDoanhThuTheoQuy.setFocusable(false);
        btnDoanhThuTheoQuy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDoanhThuTheoQuy.setIconTextGap(25);
        btnDoanhThuTheoQuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoanhThuTheoQuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoanhThuTheoQuyMouseExited(evt);
            }
        });
        btnDoanhThuTheoQuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoanhThuTheoQuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyDoanhThuLayout = new javax.swing.GroupLayout(pnlQuanLyDoanhThu);
        pnlQuanLyDoanhThu.setLayout(pnlQuanLyDoanhThuLayout);
        pnlQuanLyDoanhThuLayout.setHorizontalGroup(
            pnlQuanLyDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuanLyDoanhThuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoanhThuTheoQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuanLyDoanhThuLayout.setVerticalGroup(
            pnlQuanLyDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDoanhThuTheoQuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlQuanLyDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 531, 230, -1));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 800));

        pnlHeader.setBackground(new java.awt.Color(235, 235, 235));
        pnlHeader.setMinimumSize(new java.awt.Dimension(990, 70));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1090, 70));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSlogan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(51, 51, 51));
        lblSlogan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/running-shoe.png"))); // NOI18N
        lblSlogan.setText("HỆ THỐNG BÁN GIÀY CHÍNH HÃNG");
        lblSlogan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblSlogan.setIconTextGap(8);
        pnlHeader.add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 23, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/closeMain.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlHeader.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minusMain.png"))); // NOI18N
        btnMinus.setBorder(null);
        btnMinus.setBorderPainted(false);
        btnMinus.setContentAreaFilled(false);
        btnMinus.setDefaultCapable(false);
        btnMinus.setFocusPainted(false);
        btnMinus.setFocusable(false);
        btnMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinusMouseExited(evt);
            }
        });
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        pnlHeader.add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setDefaultCapable(false);
        btnMenu.setFocusPainted(false);
        btnMenu.setFocusable(false);
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        pnlHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        pnlSubMenu.setLayout(new java.awt.CardLayout());

        pnlSubQuanLyGiay.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubQuanLyGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyGiayMouseExited(evt);
            }
        });
        pnlSubQuanLyGiay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSubQuanLyGiay_Giay.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubQuanLyGiay_Giay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyGiay_GiayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyGiay_GiayMouseExited(evt);
            }
        });

        btnGiay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGiay.setForeground(new java.awt.Color(255, 255, 255));
        btnGiay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/shoes (1).png"))); // NOI18N
        btnGiay.setText("Giày");
        btnGiay.setBorder(null);
        btnGiay.setBorderPainted(false);
        btnGiay.setContentAreaFilled(false);
        btnGiay.setDefaultCapable(false);
        btnGiay.setFocusPainted(false);
        btnGiay.setFocusable(false);
        btnGiay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGiay.setIconTextGap(13);
        btnGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGiayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGiayMouseExited(evt);
            }
        });
        btnGiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubQuanLyGiay_GiayLayout = new javax.swing.GroupLayout(pnlSubQuanLyGiay_Giay);
        pnlSubQuanLyGiay_Giay.setLayout(pnlSubQuanLyGiay_GiayLayout);
        pnlSubQuanLyGiay_GiayLayout.setHorizontalGroup(
            pnlSubQuanLyGiay_GiayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyGiay_GiayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlSubQuanLyGiay_GiayLayout.setVerticalGroup(
            pnlSubQuanLyGiay_GiayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyGiay_GiayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGiay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubQuanLyGiay.add(pnlSubQuanLyGiay_Giay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 200, -1));

        pnlSubQuanLyGiay_DichVu.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubQuanLyGiay_DichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyGiay_DichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyGiay_DichVuMouseExited(evt);
            }
        });

        btnDichVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDichVu.setForeground(new java.awt.Color(255, 255, 255));
        btnDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/golf-shoes.png"))); // NOI18N
        btnDichVu.setText("Dịch vụ");
        btnDichVu.setBorder(null);
        btnDichVu.setBorderPainted(false);
        btnDichVu.setContentAreaFilled(false);
        btnDichVu.setDefaultCapable(false);
        btnDichVu.setFocusPainted(false);
        btnDichVu.setFocusable(false);
        btnDichVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDichVu.setIconTextGap(13);
        btnDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDichVuMouseExited(evt);
            }
        });
        btnDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubQuanLyGiay_DichVuLayout = new javax.swing.GroupLayout(pnlSubQuanLyGiay_DichVu);
        pnlSubQuanLyGiay_DichVu.setLayout(pnlSubQuanLyGiay_DichVuLayout);
        pnlSubQuanLyGiay_DichVuLayout.setHorizontalGroup(
            pnlSubQuanLyGiay_DichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyGiay_DichVuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlSubQuanLyGiay_DichVuLayout.setVerticalGroup(
            pnlSubQuanLyGiay_DichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyGiay_DichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDichVu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubQuanLyGiay.add(pnlSubQuanLyGiay_DichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, -1));

        pnlSubMenu.add(pnlSubQuanLyGiay, "card3");

        pnlSubQuanLyNhapHang.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubQuanLyNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyNhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyNhapHangMouseExited(evt);
            }
        });
        pnlSubQuanLyNhapHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSubQuanLyNhapHang_ChuyenBayNhapHang.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubQuanLyNhapHang_ChuyenBayNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyNhapHang_ChuyenBayNhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyNhapHang_ChuyenBayNhapHangMouseExited(evt);
            }
        });

        btnChuyenBayNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChuyenBayNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnChuyenBayNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/adidas.png"))); // NOI18N
        btnChuyenBayNhap.setText("Chuyến bay nhập ");
        btnChuyenBayNhap.setActionCommand("btnChuyenBay");
        btnChuyenBayNhap.setBorder(null);
        btnChuyenBayNhap.setBorderPainted(false);
        btnChuyenBayNhap.setContentAreaFilled(false);
        btnChuyenBayNhap.setDefaultCapable(false);
        btnChuyenBayNhap.setFocusPainted(false);
        btnChuyenBayNhap.setFocusable(false);
        btnChuyenBayNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChuyenBayNhap.setIconTextGap(13);
        btnChuyenBayNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChuyenBayNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChuyenBayNhapMouseExited(evt);
            }
        });
        btnChuyenBayNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBayNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubQuanLyNhapHang_ChuyenBayNhapHangLayout = new javax.swing.GroupLayout(pnlSubQuanLyNhapHang_ChuyenBayNhapHang);
        pnlSubQuanLyNhapHang_ChuyenBayNhapHang.setLayout(pnlSubQuanLyNhapHang_ChuyenBayNhapHangLayout);
        pnlSubQuanLyNhapHang_ChuyenBayNhapHangLayout.setHorizontalGroup(
            pnlSubQuanLyNhapHang_ChuyenBayNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyNhapHang_ChuyenBayNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChuyenBayNhap)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlSubQuanLyNhapHang_ChuyenBayNhapHangLayout.setVerticalGroup(
            pnlSubQuanLyNhapHang_ChuyenBayNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubQuanLyNhapHang_ChuyenBayNhapHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChuyenBayNhap)
                .addContainerGap())
        );

        pnlSubQuanLyNhapHang.add(pnlSubQuanLyNhapHang_ChuyenBayNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, -1));

        pnlSubQuanLyNhapHang_HangGiay.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubQuanLyNhapHang_HangGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyNhapHang_HangGiayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyNhapHang_HangGiayMouseExited(evt);
            }
        });

        btnHangGiay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHangGiay.setForeground(new java.awt.Color(255, 255, 255));
        btnHangGiay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nike (1).png"))); // NOI18N
        btnHangGiay.setText("Hãng giày");
        btnHangGiay.setBorder(null);
        btnHangGiay.setBorderPainted(false);
        btnHangGiay.setContentAreaFilled(false);
        btnHangGiay.setDefaultCapable(false);
        btnHangGiay.setFocusPainted(false);
        btnHangGiay.setFocusable(false);
        btnHangGiay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHangGiay.setIconTextGap(13);
        btnHangGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHangGiayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHangGiayMouseExited(evt);
            }
        });
        btnHangGiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangGiayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubQuanLyNhapHang_HangGiayLayout = new javax.swing.GroupLayout(pnlSubQuanLyNhapHang_HangGiay);
        pnlSubQuanLyNhapHang_HangGiay.setLayout(pnlSubQuanLyNhapHang_HangGiayLayout);
        pnlSubQuanLyNhapHang_HangGiayLayout.setHorizontalGroup(
            pnlSubQuanLyNhapHang_HangGiayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyNhapHang_HangGiayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHangGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlSubQuanLyNhapHang_HangGiayLayout.setVerticalGroup(
            pnlSubQuanLyNhapHang_HangGiayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyNhapHang_HangGiayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHangGiay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubQuanLyNhapHang.add(pnlSubQuanLyNhapHang_HangGiay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, -1));

        pnlSubQuanLyNhapHang_NhapHang.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubQuanLyNhapHang_NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyNhapHang_NhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubQuanLyNhapHang_NhapHangMouseExited(evt);
            }
        });

        btnNhapHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/adidas (1).png"))); // NOI18N
        btnNhapHang.setText("Nhập Hàng");
        btnNhapHang.setBorder(null);
        btnNhapHang.setBorderPainted(false);
        btnNhapHang.setContentAreaFilled(false);
        btnNhapHang.setDefaultCapable(false);
        btnNhapHang.setFocusPainted(false);
        btnNhapHang.setFocusable(false);
        btnNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhapHang.setIconTextGap(13);
        btnNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhapHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhapHangMouseExited(evt);
            }
        });
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubQuanLyNhapHang_NhapHangLayout = new javax.swing.GroupLayout(pnlSubQuanLyNhapHang_NhapHang);
        pnlSubQuanLyNhapHang_NhapHang.setLayout(pnlSubQuanLyNhapHang_NhapHangLayout);
        pnlSubQuanLyNhapHang_NhapHangLayout.setHorizontalGroup(
            pnlSubQuanLyNhapHang_NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyNhapHang_NhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlSubQuanLyNhapHang_NhapHangLayout.setVerticalGroup(
            pnlSubQuanLyNhapHang_NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubQuanLyNhapHang_NhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNhapHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubQuanLyNhapHang.add(pnlSubQuanLyNhapHang_NhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, -1));

        pnlSubMenu.add(pnlSubQuanLyNhapHang, "card4");

        pnlSubThanhToan.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubThanhToanMouseExited(evt);
            }
        });
        pnlSubThanhToan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSubThanhToan_HD.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubThanhToan_HD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubThanhToan_HDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubThanhToan_HDMouseExited(evt);
            }
        });

        btnHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bill.png"))); // NOI18N
        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.setBorder(null);
        btnHoaDon.setBorderPainted(false);
        btnHoaDon.setContentAreaFilled(false);
        btnHoaDon.setDefaultCapable(false);
        btnHoaDon.setFocusPainted(false);
        btnHoaDon.setFocusable(false);
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHoaDon.setIconTextGap(13);
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseExited(evt);
            }
        });
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubThanhToan_HDLayout = new javax.swing.GroupLayout(pnlSubThanhToan_HD);
        pnlSubThanhToan_HD.setLayout(pnlSubThanhToan_HDLayout);
        pnlSubThanhToan_HDLayout.setHorizontalGroup(
            pnlSubThanhToan_HDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubThanhToan_HDLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSubThanhToan_HDLayout.setVerticalGroup(
            pnlSubThanhToan_HDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubThanhToan_HDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSubThanhToan.add(pnlSubThanhToan_HD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 190, -1));
        pnlSubThanhToan_HD.getAccessibleContext().setAccessibleParent(pnlSubMenu);

        pnlSubThanhToan_HDCT.setBackground(new java.awt.Color(51, 51, 51));
        pnlSubThanhToan_HDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSubThanhToan_HDCTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubThanhToan_HDCTMouseExited(evt);
            }
        });

        btnHDCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHDCT.setForeground(new java.awt.Color(255, 255, 255));
        btnHDCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/billDetail.png"))); // NOI18N
        btnHDCT.setText("Hóa đơn chi tiết");
        btnHDCT.setActionCommand("btnHoaDonChiTiet");
        btnHDCT.setBorder(null);
        btnHDCT.setBorderPainted(false);
        btnHDCT.setContentAreaFilled(false);
        btnHDCT.setDefaultCapable(false);
        btnHDCT.setFocusPainted(false);
        btnHDCT.setFocusable(false);
        btnHDCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHDCT.setIconTextGap(13);
        btnHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHDCTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHDCTMouseExited(evt);
            }
        });
        btnHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubThanhToan_HDCTLayout = new javax.swing.GroupLayout(pnlSubThanhToan_HDCT);
        pnlSubThanhToan_HDCT.setLayout(pnlSubThanhToan_HDCTLayout);
        pnlSubThanhToan_HDCTLayout.setHorizontalGroup(
            pnlSubThanhToan_HDCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubThanhToan_HDCTLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btnHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSubThanhToan_HDCTLayout.setVerticalGroup(
            pnlSubThanhToan_HDCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubThanhToan_HDCTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHDCT)
                .addContainerGap())
        );

        pnlSubThanhToan.add(pnlSubThanhToan_HDCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 190, -1));

        pnlSubMenu.add(pnlSubThanhToan, "pnlSThanhToan");

        getContentPane().add(pnlSubMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 200, 310));

        pnlContent.setBackground(new java.awt.Color(211, 211, 211));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbpForm.setBackground(new java.awt.Color(204, 255, 102));
        pnlContent.add(tbpForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1070, 740));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 1070, 700));

        pnlFooter.setBackground(new java.awt.Color(0, 0, 0));
        pnlFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Design by TeamSNKA");
        pnlFooter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, -1, 30));

        getContentPane().add(pnlFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 1300, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadOpenForm();
    }//GEN-LAST:event_formWindowOpened

    private void pnlSubThanhToanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToanMouseExited
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_pnlSubThanhToanMouseExited

    private void pnlSubThanhToan_HDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToan_HDMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubThanhToan_HDMouseEntered

    private void pnlSubThanhToan_HDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToan_HDMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubThanhToan_HDMouseExited

    private void pnlSubThanhToan_HDCTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToan_HDCTMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubThanhToan_HDCTMouseEntered

    private void pnlSubThanhToan_HDCTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubThanhToan_HDCTMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubThanhToan_HDCTMouseExited

    private void pnlSubQuanLyGiayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyGiayMouseExited
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_pnlSubQuanLyGiayMouseExited

    private void pnlSubQuanLyGiay_GiayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyGiay_GiayMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyGiay_GiayMouseEntered

    private void pnlSubQuanLyGiay_GiayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyGiay_GiayMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyGiay_GiayMouseExited

    private void pnlSubQuanLyGiay_DichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyGiay_DichVuMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyGiay_DichVuMouseEntered

    private void pnlSubQuanLyGiay_DichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyGiay_DichVuMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyGiay_DichVuMouseExited

    private void pnlSubQuanLyNhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyNhapHangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlSubQuanLyNhapHangMouseEntered

    private void pnlSubQuanLyNhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyNhapHangMouseExited
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_pnlSubQuanLyNhapHangMouseExited

    private void pnlSubQuanLyNhapHang_ChuyenBayNhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyNhapHang_ChuyenBayNhapHangMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyNhapHang_ChuyenBayNhapHangMouseEntered

    private void pnlSubQuanLyNhapHang_ChuyenBayNhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyNhapHang_ChuyenBayNhapHangMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyNhapHang_ChuyenBayNhapHangMouseExited

    private void pnlSubQuanLyNhapHang_HangGiayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyNhapHang_HangGiayMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyNhapHang_HangGiayMouseEntered

    private void pnlSubQuanLyNhapHang_HangGiayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyNhapHang_HangGiayMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyNhapHang_HangGiayMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        changeIcon(1, btnClose, "src//Icon//closeMainGray.png");
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        changeIcon(2, btnClose, "src//Icon//closeMain.png");
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        minus();
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMinusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseEntered
        changeIcon(1, btnMinus, "src//Icon//minusMainGray.png");
    }//GEN-LAST:event_btnMinusMouseEntered

    private void btnMinusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseExited
        changeIcon(2, btnMinus, "src//Icon//minusMain.png");
    }//GEN-LAST:event_btnMinusMouseExited

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        tbpForm.removeAll();
        frmTrangChu tc = new frmTrangChu();
        tbpForm.addTab("", null, tc.getContentPane().getComponentAt(0, 0), null);
        lblUser.setText("NULL");
        lblChucVu.setText(null);
        frmLogin.tenDN = "";
        frmLogin.vt = "";
        login();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        changeIcon(1, btnLogout, "src//Icon//logoutGray.png");
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        changeIcon(2, btnLogout, "src//Icon//logout.png");
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        JOptionPane.showMessageDialog(this, "Đang phát triển!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
        changeIcon(1, btnSetting, "src//Icon//settingGray.png");
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseExited
        changeIcon(2, btnSetting, "src//Icon//setting.png");
    }//GEN-LAST:event_btnSettingMouseExited

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        JOptionPane.showMessageDialog(this, "Đang phát triển!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseEntered
        changeIcon(1, btnAccount, "src//Icon//groupGray.png");
    }//GEN-LAST:event_btnAccountMouseEntered

    private void btnAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseExited
        changeIcon(2, btnAccount, "src//Icon//group.png");
    }//GEN-LAST:event_btnAccountMouseExited

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        //menu();
        JOptionPane.showMessageDialog(this, "Đang phát triển!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        changeIcon(2, btnMenu, "src//Icon//menu.png");
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        changeIcon(1, btnMenu, "src//Icon//menuGray.png");
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        tbpForm.removeAll();
        frmTrangChu tc = new frmTrangChu();
        tbpForm.addTab("", null, tc.getContentPane().getComponentAt(0, 0), null);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseEntered
        hover(1, pnlTrangChu);
    }//GEN-LAST:event_btnTrangChuMouseEntered

    private void btnTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangChuMouseExited
        hover(2, pnlTrangChu);
    }//GEN-LAST:event_btnTrangChuMouseExited

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        if (!chucVu.isEmpty()) {
            tbpForm.removeAll();
            frmQuanLyKhachHang kh = new frmQuanLyKhachHang(chucVu);
            tbpForm.addTab("", null, kh.getContentPane().getComponentAt(0, 0), null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseEntered
        hover(1, pnlKhachHang);
    }//GEN-LAST:event_btnKhachHangMouseEntered

    private void btnKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseExited
        hover(2, pnlKhachHang);
    }//GEN-LAST:event_btnKhachHangMouseExited

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        if (!chucVu.isEmpty()) {
            tbpForm.removeAll();
            frmNhanVien nv = new frmNhanVien(chucVu);
            tbpForm.addTab("", null, nv.getContentPane().getComponentAt(0, 0), null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseEntered
        hover(1, pnlNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseEntered

    private void btnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseExited
        hover(2, pnlNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseExited

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        if (!chucVu.isEmpty()) {
            showHideSubMenu(showHideSubMenu_ThanhToan, pnlSubThanhToan);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnThanhtoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhtoanMouseEntered
        hover(1, pnlThanhToan);
    }//GEN-LAST:event_btnThanhtoanMouseEntered

    private void btnThanhtoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhtoanMouseExited
        hover(2, pnlThanhToan);
    }//GEN-LAST:event_btnThanhtoanMouseExited

    private void btnQuanLyGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyGiayActionPerformed
        if (!chucVu.isEmpty()) {
            showHideSubMenu(showHideSubMenu_Ve, pnlSubQuanLyGiay);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnQuanLyGiayActionPerformed

    private void btnQuanLyGiayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyGiayMouseEntered
        hover(1, pnlQuanLyGiay);
    }//GEN-LAST:event_btnQuanLyGiayMouseEntered

    private void btnQuanLyGiayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyGiayMouseExited
        hover(2, pnlQuanLyGiay);
    }//GEN-LAST:event_btnQuanLyGiayMouseExited

    private void btnQuanLyNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhapHangActionPerformed
        if (!chucVu.isEmpty()) {

            showHideSubMenu(showHideSubMenu_ChuyenBay, pnlSubQuanLyNhapHang);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnQuanLyNhapHangActionPerformed

    private void btnQuanLyNhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNhapHangMouseEntered
        hover(1, pnlQuanLyNhapHang);
    }//GEN-LAST:event_btnQuanLyNhapHangMouseEntered

    private void btnQuanLyNhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNhapHangMouseExited
        hover(2, pnlQuanLyNhapHang);
    }//GEN-LAST:event_btnQuanLyNhapHangMouseExited

    private void btnDoanhThuTheoQuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoanhThuTheoQuyActionPerformed
        if(!chucVu.isEmpty() && chucVu.equals("Trưởng phòng")){
            tbpForm.removeAll();
            frmDoanhThuTheoThang quy = new frmDoanhThuTheoThang();
            tbpForm.addTab("", null, quy.getContentPane().getComponentAt(0, 0), null);
        }else{
            JOptionPane.showMessageDialog(this, "Chỉ cấp quyền admin!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDoanhThuTheoQuyActionPerformed

    private void btnDoanhThuTheoQuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuTheoQuyMouseEntered
        hover(1, pnlQuanLyDoanhThu);
    }//GEN-LAST:event_btnDoanhThuTheoQuyMouseEntered

    private void btnDoanhThuTheoQuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhThuTheoQuyMouseExited
        hover(2, pnlQuanLyDoanhThu);
    }//GEN-LAST:event_btnDoanhThuTheoQuyMouseExited

    private void btnGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiayActionPerformed
        tbpForm.removeAll();
        frmQuanLyGiay vemb = new frmQuanLyGiay(chucVu);
        tbpForm.addTab("", null, vemb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnGiayActionPerformed

    private void btnGiayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGiayMouseEntered
        hover(1, pnlSubQuanLyGiay_Giay);
    }//GEN-LAST:event_btnGiayMouseEntered

    private void btnGiayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGiayMouseExited
        hover(2, pnlSubQuanLyGiay_Giay);
    }//GEN-LAST:event_btnGiayMouseExited

    private void btnDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuActionPerformed
        tbpForm.removeAll();
        frmDichVu dv = new frmDichVu(chucVu);
        tbpForm.addTab("", null, dv.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnDichVuActionPerformed

    private void btnDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseEntered
        hover(1, pnlSubQuanLyGiay_DichVu);
    }//GEN-LAST:event_btnDichVuMouseEntered

    private void btnDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseExited
        hover(2, pnlSubQuanLyGiay_DichVu);
    }//GEN-LAST:event_btnDichVuMouseExited

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        tbpForm.removeAll();
        frmHoaDon hd = new frmHoaDon(chucVu);
        tbpForm.addTab("", null, hd.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseEntered
        hover(1, pnlSubThanhToan_HD);
    }//GEN-LAST:event_btnHoaDonMouseEntered

    private void btnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseExited
        hover(2, pnlSubThanhToan_HD);
    }//GEN-LAST:event_btnHoaDonMouseExited

    private void btnHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDCTActionPerformed
        tbpForm.removeAll();
        frmHoaDonChiTiet cthd = new frmHoaDonChiTiet(chucVu);
        tbpForm.addTab("", null, cthd.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnHDCTActionPerformed

    private void btnHDCTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDCTMouseEntered
        hover(1, pnlSubThanhToan_HDCT);
    }//GEN-LAST:event_btnHDCTMouseEntered

    private void btnHDCTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDCTMouseExited
        hover(2, pnlSubThanhToan_HDCT);
    }//GEN-LAST:event_btnHDCTMouseExited

    private void btnChuyenBayNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBayNhapActionPerformed
        tbpForm.removeAll();
        frmChuyenBayNhapHang cb = new frmChuyenBayNhapHang(chucVu);
        tbpForm.addTab("", null, cb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnChuyenBayNhapActionPerformed

    private void btnChuyenBayNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChuyenBayNhapMouseEntered
        hover(1, pnlSubQuanLyNhapHang_ChuyenBayNhapHang);
    }//GEN-LAST:event_btnChuyenBayNhapMouseEntered

    private void btnChuyenBayNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChuyenBayNhapMouseExited
        hover(2, pnlSubQuanLyNhapHang_ChuyenBayNhapHang);
    }//GEN-LAST:event_btnChuyenBayNhapMouseExited

    private void btnHangGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangGiayActionPerformed
        tbpForm.removeAll();
        frmQuanLyThuongHieuGiay hmb = new frmQuanLyThuongHieuGiay(chucVu);
        tbpForm.addTab("", null, hmb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnHangGiayActionPerformed

    private void btnHangGiayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHangGiayMouseEntered
        hover(1, pnlSubQuanLyNhapHang_HangGiay);
    }//GEN-LAST:event_btnHangGiayMouseEntered

    private void btnHangGiayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHangGiayMouseExited
        hover(2, pnlSubQuanLyNhapHang_HangGiay);
    }//GEN-LAST:event_btnHangGiayMouseExited

    private void btnNhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapHangMouseEntered
        hover(1, pnlSubQuanLyNhapHang_NhapHang);
    }//GEN-LAST:event_btnNhapHangMouseEntered

    private void btnNhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapHangMouseExited
        hover(2, pnlSubQuanLyNhapHang_NhapHang);
    }//GEN-LAST:event_btnNhapHangMouseExited

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        tbpForm.removeAll();
        frmQuanLyNhapHang mb = new frmQuanLyNhapHang(chucVu);
        tbpForm.addTab("", null, mb.getContentPane().getComponentAt(0, 0), null);
        pnlSubMenu.setVisible(false);
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void pnlSubQuanLyNhapHang_NhapHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyNhapHang_NhapHangMouseEntered
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyNhapHang_NhapHangMouseEntered

    private void pnlSubQuanLyNhapHang_NhapHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubQuanLyNhapHang_NhapHangMouseExited
        pnlSubMenu.setVisible(true);
    }//GEN-LAST:event_pnlSubQuanLyNhapHang_NhapHangMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnChuyenBayNhap;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDichVu;
    private javax.swing.JButton btnDoanhThuTheoQuy;
    private javax.swing.JButton btnGiay;
    private javax.swing.JButton btnHDCT;
    private javax.swing.JButton btnHangGiay;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnQuanLyGiay;
    private javax.swing.JButton btnQuanLyNhapHang;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlQuanLyDoanhThu;
    private javax.swing.JPanel pnlQuanLyGiay;
    private javax.swing.JPanel pnlQuanLyNhapHang;
    private javax.swing.JPanel pnlSubMenu;
    private javax.swing.JPanel pnlSubQuanLyGiay;
    private javax.swing.JPanel pnlSubQuanLyGiay_DichVu;
    private javax.swing.JPanel pnlSubQuanLyGiay_Giay;
    private javax.swing.JPanel pnlSubQuanLyNhapHang_ChuyenBayNhapHang;
    private javax.swing.JPanel pnlSubQuanLyNhapHang_HangGiay;
    private javax.swing.JPanel pnlSubQuanLyNhapHang_NhapHang;
    private javax.swing.JPanel pnlSubThanhToan;
    private javax.swing.JPanel pnlSubThanhToan_HD;
    private javax.swing.JPanel pnlSubThanhToan_HDCT;
    private javax.swing.JPanel pnlThanhToan;
    private javax.swing.JPanel pnlTrangChu;
    private javax.swing.JTabbedPane tbpForm;
    // End of variables declaration//GEN-END:variables
}
